- package.json
- tsconfig.json
It is hard to find anything if there is no particular order to the properties. Alphabetical is the most straight forward way in most cases. I sorted using the commands below. 
```
cat package.json | jq -S . | tee package.json
cat tsconfig.json | jq -S . | tee tsconfig.json
```
> sort package.json and tsconfig.json

- .github/workflows/typescript.yaml
- src/component/app/index.tsx
- src/index.tsx
- src/reportWebVitals.ts
As discussed we want to address any formatting issues by trying out https://github.com/prettier/prettier. 
```
npm install prettier --global
```
This pull request adds a workflow to verify `prettier` formatting was applied to all `.ts` and `.tsx` files in the `src` directory. There are plugins for Atom and vsCode which everyone should use to **format on save**. That makes life a whole lot easier. I just ran `prettier` against the current codebase in `main`. 
```
prettier -w $(find ./src/ -name "*.ts" -o -name "*.tsx")
```
> add typescript workflow

- .github/workflows/docker-ts.yaml
- Dockerfile
- README.md
- hlm/webclient/Chart.yaml
- hlm/webclient/templates/deployment.yaml
- hlm/webclient/templates/destination-rule.yaml
- hlm/webclient/templates/service.yaml
- hlm/webclient/templates/virtual-service.yaml
- hlm/webclient/values.yaml
This is for the deployment pipeline. We use helm for templating and deployments on Kubernetes. This works locally using Kind as well as in the cloud with AWS.
> add helm templates for kubernetes deployment

- public/index.html
Fixes #17  by extending root div to 100% height
> fix screen background height

- src/component/actionbar/index.tsx
- src/component/editor/compose/index.tsx
Fixes #17 to show send button when user types in editor.
> Send state

- plasmic.lock
- src/component/plasmic/shared/PlasmicActionBar.module.css
- src/component/plasmic/shared/PlasmicActionBar.tsx
generated code pull request
named component in plasmic
> **generated code** named send button component in plasmic

- plasmic.lock
- src/component/plasmic/plasmic__default_style.module.css
- src/component/plasmic/shared/PlasmicActionBar.module.css
- src/component/plasmic/shared/PlasmicActionBar.tsx
Added error view with props in Plasmic.
All these changes are generated code.
> error state

- plasmic.lock
- src/component/actionbar/index.tsx
- src/component/plasmic/home/PlasmicHome.module.css
- src/component/plasmic/home/PlasmicHome.tsx
- src/component/plasmic/shared/PlasmicActionBar.module.css
- src/component/plasmic/shared/PlasmicActionBar.tsx
POC error view. We don't yet have a check to trigger a validation error message.
> poc error container

- package-lock.json
- package.json
- src/component/actionbar/index.tsx
- src/component/editor/compose/index.tsx
- src/component/editor/config/initialValues.ts
Fixes #44 
Removing placeholder fixes behavior
> fix slate-plugins german bug

- src/component/editor/config/initialValues.ts
update action bar initial value
Fixes #48
> update action bar initial value

- src/component/plasmic/shared/PlasmicActionsColumn.module.css
- src/component/plasmic/shared/PlasmicActionsColumn.tsx
design adjustment
Cutoff at 4 characters.
> cutoff number value

- src/component/editor/compose/index.tsx
- src/component/home/index.tsx
Editor won't extend beyond 188 pixels in height.
> limit height of editor poc

- plasmic.lock
- src/component/editor/compose/index.tsx
- src/component/home/index.tsx
- src/component/plasmic/shared/PlasmicActionBar.tsx
- force character limit so user cannot type more than 240 characters
- tie progress to stored value
> Restrict characters4

- plasmic.lock
- src/component/actionbar/index.tsx
- src/component/editor/compose/index.tsx
- src/component/home/index.tsx
- src/component/plasmic/home/PlasmicHome.tsx
- src/component/plasmic/shared/PlasmicActionBar.module.css
- src/component/plasmic/shared/PlasmicActionBar.tsx
Fixed a few bugs related to new progress status:
1. lift up state to clear progress bar on update publish
2. clear number error onChange
> bug fix and lift up state

- package-lock.json
- package.json
- plasmic.lock
- src/component/actionbar/index.tsx
- src/component/editor/compose/index.tsx
- src/component/home/index.tsx
- src/component/plasmic/home/PlasmicHome.tsx
- src/component/plasmic/shared/PlasmicActionBar.module.css
- src/component/plasmic/shared/PlasmicActionBar.tsx
POC progress bar
- installed material-ui
- replaced container component in plasmic with circular progress bar
- linked circular progress bar to editor onChange event
> progress proof of concept

- package-lock.json
- package.json
- plasmic.json
- plasmic.lock
- src/component/actionbar/index.tsx
- src/component/editor/compose/index.tsx
- src/component/home/index.tsx
- src/component/plasmic/home/PlasmicHome.tsx
- src/component/plasmic/plasmic__default_style.module.css
- src/component/plasmic/shared/PlasmicActionBar.module.css
- src/component/plasmic/shared/PlasmicActionBar.tsx
- src/component/plasmic/shared/PlasmicUpdateContent.tsx
Updated design for progress bar
- new variant state on compose update component
- progress bar placeholder
> update design for progress bar

- package-lock.json
- package.json
- src/component/home/index.tsx
- src/component/linechart/index.tsx
- src/component/metric/index.tsx
- src/component/update/index.tsx
- src/component/updatecontent/index.tsx
POC for integrating graph
- lift up graph data to home page
- create metrics hook to store state
- send shared data via props to child componets
- install date-fns to manipulate date on create
> Graph integration poc

- plasmic.lock
- src/component/plasmic/home/PlasmicHome.tsx
- src/component/plasmic/shared/PlasmicActionBar.module.css
- src/component/plasmic/shared/PlasmicActionBar.tsx
from no text, typing caused the updates to push down.
Adjusted padding to compensate.
> fix padding bug when typing in actionbar

- src/component/actionbar/index.tsx
- src/component/editor/compose/index.tsx
- src/component/home/index.tsx
no new functionality.
- create custom useEditor hook to make editor shape explicit
- create editor interface
> refactor editor hooks

- plasmic.json
- plasmic.lock
- src/component/home/index.tsx
- src/component/plasmic/home/PlasmicHome.tsx
- toggle button image when timeline input has value
> toggle button when addTimeline has value

- plasmic.json
- plasmic.lock
- src/component/home/index.tsx
- src/component/plasmic/home/PlasmicHome.tsx
This reverts commit eb3b719945fb9c59474f5fddf257533e99c03869.
> Revert "toggle button when addTimeline has value (#74)"

- package-lock.json
- package.json
- plasmic.lock
- src/component/editor/read/index.tsx
- src/component/home/index.tsx
- src/component/plasmic/home/PlasmicHome.module.css
- src/component/plasmic/home/PlasmicHome.tsx
- src/component/plasmic/shared/PlasmicTimelineItem.module.css
- src/component/plasmic/shared/PlasmicTimelineItem.tsx
- src/component/timelineitem/index.tsx
- src/component/update/index.tsx
- src/component/updatecontent/index.tsx
Work:
- strengthen type by keeping editor props to Node[] type
- added timeline item type
- added setTimelineItems hook
- added default timeline items array
- extended TimelineItem props
Next:
- clear add timeline on success
- change button on input value change
> Sidebar behavior

- package-lock.json
- package.json
- plasmic.json
- plasmic.lock
- src/component/home/index.tsx
- src/component/plasmic/home/PlasmicHome.module.css
- src/component/plasmic/home/PlasmicHome.tsx
- src/component/plasmic/shared/PlasmicActionBar.module.css
- src/component/plasmic/shared/PlasmicActionsColumn.module.css
- src/component/plasmic/shared/PlasmicIconButton.module.css
- src/component/plasmic/shared/PlasmicTimelineItem.module.css
- src/component/plasmic/shared/PlasmicUpdate.module.css
- src/component/plasmic/shared/icons/PlasmicIcon__IconCheck.tsx
- icon on value change in timeline input
- clicking plus when value is empty toggles sidebar
- update plasmic
> fix icon bug and update plasmic

- src/component/home/index.tsx
- src/component/metric/index.tsx
- src/component/sidebar/index.tsx
- src/component/sidebaritem/index.tsx
- src/component/update/index.tsx
- sidebar navigation highlights current item
- update default data to work with different timelines
> poc sidebar navigation

- package-lock.json
- package.json
- plasmic.json
- plasmic.lock
- src/component/home/index.tsx
- src/component/plasmic/home/PlasmicHome.module.css
- src/component/plasmic/home/PlasmicHome.tsx
- src/component/plasmic/shared/PlasmicActionBar.module.css
- src/component/plasmic/shared/PlasmicActionBar.tsx
- src/component/plasmic/shared/PlasmicActionsColumn.module.css
- src/component/plasmic/shared/PlasmicActionsColumn.tsx
- src/component/plasmic/shared/PlasmicIconButton.tsx
- src/component/plasmic/shared/PlasmicMetric.tsx
- src/component/plasmic/shared/PlasmicSidebar.module.css
- src/component/plasmic/shared/PlasmicSidebar.tsx
- src/component/plasmic/shared/PlasmicSidebarItem.module.css
- src/component/plasmic/shared/PlasmicSidebarItem.tsx
- src/component/plasmic/shared/PlasmicUpdate.module.css
- src/component/plasmic/shared/PlasmicUpdate.tsx
- src/component/plasmic/shared/PlasmicUpdateContent.module.css
- src/component/plasmic/shared/PlasmicUpdateContent.tsx
- src/component/plasmic/shared/icons/PlasmicIcon__IconClose.tsx
- src/component/plasmic/shared/icons/PlasmicIcon__IconMenuOpen.tsx
- src/component/sidebar/index.tsx
Design Adjustments
- Add sidebar icon to toggle sidebar Fixes issue #83 and Fixes issue #82 
- Made sidebar icons same size in hide and show state; Fixes issue #81 
- Adjusting sidebar item padding on hover Fixes issue #84
> Design bugs

- plasmic.json
- plasmic.lock
- src/component/home/index.tsx
- src/component/plasmic/home/PlasmicHome.module.css
- src/component/plasmic/home/PlasmicHome.tsx
- src/component/plasmic/shared/PlasmicGlobalVariant__Screen.tsx
- src/component/plasmic/shared/PlasmicSidebar.module.css
- add sidebar scroll
- adjust sidebar icon positions on animations
- Fixes #90
> Screen height

- src/module/api/metric/search/index.ts
- src/module/api/metricupdate/create/index.ts
- src/module/api/timeline/create/index.ts
- src/module/api/update/search/index.ts
> add alerts to backend error codes

- src/component/sidebar/index.tsx
- src/component/update/index.tsx
> prevent duplicate timelines and fix sorting

- src/component/editor/compose/index.tsx
- src/component/home/index.tsx
- src/module/api/metricupdate/create/index.ts
> fix metrics order bug;

- public/index.html
added smartlook code to public html
> adding smartlook code

- src/component/home/index.tsx
- src/component/sidebar/index.tsx
- src/module/api/timeline/create/index.ts
- src/module/api/timeline/search/index.ts
It takes awhile to load playbooks. But they work.
> poc hardcoded playbook

- src/component/home/index.tsx
- src/module/api/update/search/index.ts
- src/module/hook/update/index.ts
- src/module/interface/update/index.ts
> poc get all updates in home

- src/module/customerdata/index.ts
> update baron-fig and memo customers

- plasmic.lock
- src/component/SelectTimeline.tsx
- src/component/actionbar/index.tsx
- src/component/ant/select/index.tsx
- src/component/linechart/index.tsx
- src/component/plasmic-tokens.theo.json
- src/component/plasmic/home/PlasmicHome.module.css
- src/component/plasmic/home/PlasmicHome.tsx
- src/component/plasmic/shared/PlasmicActionBar.module.css
- src/component/plasmic/shared/PlasmicActionBar.tsx
- src/component/plasmic/shared/PlasmicSelectTimeline.module.css
- src/component/plasmic/shared/PlasmicSelectTimeline.tsx
- src/component/plasmic/shared/PlasmicSidebarItem.module.css
- src/component/plasmic/shared/PlasmicSidebarItem.tsx
- src/component/plasmic/shared/PlasmicUpdateContent.module.css
- src/component/plasmic/shared/PlasmicUpdateContent.tsx
> improve select design

- src/component/home/index.tsx
- src/module/hook/update/index.ts
> fixing duplicates and refactoring react query code

- src/component/ReplyContent.tsx
- src/component/ReplyContentSecond.tsx
- src/component/plasmic/home/PlasmicButton.module.css
- src/component/plasmic/home/PlasmicHome.module.css
- src/component/plasmic/home/PlasmicInputField.module.css
- src/component/plasmic/home/PlasmicSidebarListItem.module.css
- src/component/plasmic/home/PlasmicTimelinModal.module.css
- src/component/plasmic/home/plasmic_home.module.css
- src/component/plasmic/shared/PlasmicActionBar.module.css
- src/component/plasmic/shared/PlasmicActionsColumn.module.css
- src/component/plasmic/shared/PlasmicButton.module.css
- src/component/plasmic/shared/PlasmicDropdown.module.css
- src/component/plasmic/shared/PlasmicHeader.module.css
- src/component/plasmic/shared/PlasmicIconButton.module.css
- src/component/plasmic/shared/PlasmicMainHeader.module.css
- src/component/plasmic/shared/PlasmicModal.module.css
- src/component/plasmic/shared/PlasmicModalAlt.module.css
- src/component/plasmic/shared/PlasmicReplyContent.module.css
- src/component/plasmic/shared/PlasmicReplyContentSecond.module.css
- src/component/plasmic/shared/PlasmicReplyContentSecond.tsx
- src/component/plasmic/shared/PlasmicReplyInput.module.css
- src/component/plasmic/shared/PlasmicSelectItem.module.css
- src/component/plasmic/shared/PlasmicSelectTimeline.module.css
- src/component/plasmic/shared/PlasmicSidebar.module.css
- src/component/plasmic/shared/PlasmicSidebarItem.module.css
- src/component/plasmic/shared/PlasmicSidebarOrganizationName.tsx
- src/component/plasmic/shared/PlasmicTextInput.module.css
- src/component/plasmic/shared/PlasmicUpdateContent.module.css
- src/component/plasmic/shared/plasmic_shared.module.css
- src/component/updatecontent/index.tsx
> fix reply state glitch

- src/module/customerdata/index.ts
> update kav data

- plasmic.lock
- src/component/plasmic/shared/PlasmicContentPost.module.css
- src/component/plasmic/shared/PlasmicHome.tsx
- src/component/plasmic/shared/PlasmicMainHeader.module.css
- src/component/plasmic/shared/PlasmicMainHeader.tsx
- src/component/plasmic/shared/PlasmicPostDetails.module.css
- src/component/plasmic/shared/PlasmicPostDetails.tsx
- src/component/plasmic/shared/PlasmicProfile.module.css
- src/component/plasmic/shared/PlasmicProfile.tsx
- src/component/plasmic/shared/PlasmicProfileForm.module.css
> design update

- src/component/actionbar/index.tsx
- src/module/api/texupd/create/index.ts
> fix create update api call

- plasmic.lock
- src/component/plasmic/shared/PlasmicHeader.module.css
- src/component/plasmic/shared/PlasmicHome.module.css
- src/component/plasmic/shared/PlasmicMainHeader.module.css
- src/component/plasmic/shared/PlasmicMainHeader.tsx
- src/component/plasmic/shared/PlasmicMembers.module.css
- src/component/plasmic/shared/PlasmicPostDetails.module.css
- src/component/plasmic/shared/PlasmicReplyContent.module.css
- src/component/plasmic/shared/PlasmicReplyContent.tsx
- src/component/plasmic/shared/PlasmicSidebar.module.css
- src/component/plasmic/shared/PlasmicVentureSettings.module.css
> plasmic update

- src/component/actionbar/index.tsx
- src/component/ant/select/index.tsx
> expand timeline select

- src/component/contentpost/index.tsx
- src/component/feedupdate/index.tsx
- src/component/page/home/index.tsx
- src/component/postdetails/index.tsx
- src/component/replycontent/index.tsx
- src/component/replyinput/index.tsx
- src/module/api/message/search/index.ts
- src/module/api/update/search/index.ts
- src/module/hook/message/index.ts
- src/module/interface/message/index.ts
- src/module/interface/update/index.ts
> poc username on message

- src/component/app/index.tsx
fixes #250 
There was a typo 3 in one of the routes that I deleted.
> remove magic number

- src/component/radio/index.tsx
Fixes #246 
disabled radio group button click in create timeline
> disable create timeline permission-select

- src/component/addeditmembers/index.tsx
- src/component/addedittimeline/index.tsx
- src/component/ant/dropdown/index.tsx
- src/component/contentpost/index.tsx
- src/component/feedupdate/index.tsx
- src/component/page/joinventure/index.tsx
- src/component/postdetails/index.tsx
- src/component/profileform/index.tsx
- src/component/replycontent/index.tsx
- src/module/api/invite/create/index.ts
- src/module/api/role/delete/index.ts
- src/module/api/timeline/update/index.ts
- src/module/helpers/index.ts
- src/module/hook/message/index.ts
- src/module/hook/timeline/index.ts
- src/module/interface/user/index.ts
> fix user cache and remove extra console logs

- package-lock.json
- src/component/addeditventure/index.tsx
- src/component/inputtext/index.tsx
- src/component/main/index.tsx
- src/component/profileform/index.tsx
- src/module/hook/invite/index.ts
> fix errors

- package-lock.json
- src/component/addeditmembers/index.tsx
> fix delete self from timeline bug

- src/component/modal/index.tsx
> fix deleted venture in address bar

- package-lock.json
- package.json
- public/index.html
- src/component/app/index.tsx
adding google analytics.
A but more instrumentation required.
> add google analytics

- src/module/helpers/index.ts
- src/module/interface/email/index.ts
Fixes #256 
minimal adjustment in client. (only updated 1 variable).
Most of the changes are in email.js
> update email template variables

- src/component/postdetails/index.tsx
- src/component/replyinput/index.tsx
> Replies order

- src/component/app/index.tsx
- src/component/profileform/index.tsx
- src/module/hook/venture/index.ts
> fix create venture bug

- src/component/addeditmembers/index.tsx
- src/module/hook/user/index.ts
- tsconfig.json
Fixes https://github.com/venturemark/webclient/issues/327
> Reset member invite on success

- src/component/page/profile/index.tsx
Fixes https://github.com/venturemark/webclient/issues/344
> Redirect from profile to joinventure if accepting an invite

- src/component/feedupdate/index.tsx
I found that the users weren't being loaded when viewing replies on an update.
> Improve user loading for feedupdate component

- src/component/modal/index.tsx
- src/module/hook/user/index.ts
Fixes https://github.com/venturemark/webclient/issues/341
> Fix flash of default name (from identity provider) if name is changed during creation

- src/component/addeditmembers/index.tsx
- src/component/addeditventure/index.tsx
Fixes https://github.com/venturemark/webclient/issues/342
> Allow leading/trailing whitespace on invite email value

- src/component/actionbar/index.tsx
- src/component/addeditmembers/index.tsx
- src/component/feedupdate/index.tsx
- src/component/materialui/select/index.tsx
- src/component/memberitem/index.tsx
- src/component/profiledropdown/index.tsx
- src/module/hook/invite/index.ts
Follow-up for the previous PR.
> Refine roles

- src/component/app/VentureRoutes.tsx
- src/module/api/role/search/index.ts
- src/module/api/timeline/create/index.ts
- src/module/api/timeline/search/index.ts
- src/module/api/venture/create/index.ts
- src/module/api/venture/search/index.ts
- src/module/hook/role/index.ts
- src/module/interface/role/index.ts
Fixes https://github.com/venturemark/webclient/issues/365
> Default existing ventures and timelines to reader view until otherwise configured

- src/component/modal/index.tsx
- src/component/profileform/index.tsx
- src/module/api/user/create/index.ts
- src/module/api/user/search/index.ts
- src/module/api/user/update/index.ts
- src/module/interface/user/index.ts
For email integration roadmap issue.
> Wire up mail field in user profile based on Auth0 data

- src/component/addedittimeline/index.tsx
- src/component/addeditventure/index.tsx
- src/component/modal/index.tsx
- src/component/profileform/index.tsx
- src/module/api/timeline/update/index.ts
- src/module/api/venture/create/index.ts
- src/module/api/venture/search/index.ts
- src/module/api/venture/update/index.ts
- src/module/interface/timeline/index.ts
- src/module/interface/venture/index.ts
Fixes https://github.com/venturemark/webclient/issues/364
Fixes https://github.com/venturemark/webclient/issues/363
> Fix venture and timeline permissions edit

- src/component/header/index.tsx
- src/component/memberitem/index.tsx
- src/component/photoavatar/index.tsx
- src/component/replycontent/index.tsx
- src/component/sidebaritem/index.tsx
- src/module/hook/ui/useDropdown.ts
Fixes https://github.com/venturemark/webclient/issues/370
Dropdowns covered:
- SidebarItem
- MemberItem
- Header (profile)
- ReplyContent
> Use hook for all dropdowns

- src/component/addedittimeline/index.tsx
- src/component/feedupdate/index.tsx
- src/module/helpers/index.ts
Fixes https://github.com/venturemark/webclient/issues/390
> Fix timeline ownership check in AddEditTimeline

- src/component/addedittimeline/index.tsx
- src/component/addeditventure/index.tsx
- src/component/app/RegisteredUserRoute.tsx
- src/component/app/VentureRoutes.tsx
- src/component/main/index.tsx
- src/context/VentureContext.ts
- src/module/hook/ui/useVentures.ts
Fixes https://github.com/venturemark/webclient/issues/355
> Validate venture and timeline names for duplicates

- src/component/contentpost/index.tsx
- src/component/editor/compose/index.tsx
- src/component/feedupdate/index.tsx
- src/component/header/index.tsx
- src/component/main/index.tsx
- src/component/modal/index.tsx
- src/component/page/home/index.tsx
- src/component/page/profile/index.tsx
- src/component/radiogroup/index.tsx
- src/module/helpers/index.ts
- src/module/hook/ui/useVentures.ts
- src/module/interface/invite/index.ts
- src/module/interface/role/index.ts
- src/module/interface/timeline/index.ts
- src/module/interface/update/index.ts
- src/module/interface/venture/index.ts
Fixes https://github.com/venturemark/webclient/issues/395
> Keep post details open when clicking on a different post replies

- src/component/contentpost/index.tsx
Fixes https://github.com/venturemark/webclient/issues/455
> Fix ContentPost

- package-lock.json
- package.json
- src/component/app/AuthRoute.tsx
- src/component/app/TimelineRoutes.tsx
- src/component/app/VentureRoutes.tsx
- src/component/loadingbar/index.tsx
- src/component/page/signin/index.tsx
**READY**
https://github.com/venturemark/webclient/issues/443
Replace Preloader
https://user-images.githubusercontent.com/28189578/145396325-9ebdeda9-ca8a-438d-afde-65bb7ba2f4e1.mov
> [Issue #443] Replace Preloader

- src/component/addedittimeline/index.tsx
- src/component/addeditventure/index.tsx
- src/component/app/TimelineRoutes.tsx
- src/component/app/VentureRoutes.tsx
- src/component/app/index.tsx
- src/component/emptystate/index.tsx
- src/component/feedupdate/index.tsx
- src/component/header/index.tsx
- src/component/mainheader/index.tsx
- src/component/modal/index.tsx
- src/component/sidebaritem/index.tsx
- src/component/sidebaritemgroup/index.tsx
- src/component/timelinelink/index.tsx
- src/module/hook/timeline/index.ts
- src/module/hook/ui/useVentures.ts
- src/module/hook/venture/index.ts
- src/module/interface/timeline/index.ts
- src/module/interface/venture/index.ts
Also fixes https://github.com/venturemark/webclient/issues/462
> Use venture and timeline IDs instead of slugs for routing

- src/component/editor/index.tsx
**READY**
https://github.com/venturemark/webclient/issues/464
Posting updates doesn't reset editor
> [Issue #464] Posting updates doesn't reset editor

- src/component/actionbar/index.tsx
- src/component/app/TimelineRoutes.tsx
- src/component/app/index.tsx
- src/component/header/index.tsx
- src/context/UpdateEditorContext.ts
**READY**
https://github.com/venturemark/webclient/issues/461
Fix updates lost when clicking on a different venture
> [Issue #461] Fix updates lost when clicking on a different venture

- src/component/header/index.tsx
**READY**
https://github.com/venturemark/webclient/issues/471
Remove blue underline in the share button
> [Issue #471] Remove blue underline in the share button

- src/component/editor/index.tsx
**READY**
https://github.com/venturemark/webclient/issues/470
Weird behavior when pressing space bar in editor
> [Issue #470] Weird behavior when pressing space bar in editor

- src/component/actionbar/index.tsx
- src/component/editor/index.tsx
**READY**
https://github.com/venturemark/webclient/issues/481
Fix the issue `Slate editor crashes after posting an update`
> [Issue #481] Slate editor crashes after posting an update

- src/component/actionbar/index.tsx
**READY**
https://github.com/venturemark/webclient/issues/495
EmojiMart modal z-index
> [Issue #495] EmojiMart modal z-index

- src/module/auth/index.ts
- src/module/helpers/index.ts
Splitting out from https://github.com/venturemark/webclient/pull/458 so we can revert it easily if there are any problems.
Part of https://github.com/venturemark/webclient/issues/441
> Update redirect URL to breadcrumb.so
